# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lauraimage5

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://image5.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ad7a745a38cc4c778d7d45e446068a3f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e8a9530cb316490980250bb60a3b2fcd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: image5.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ad7a745a38cc4c778d7d45e446068a3f }}/image5:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lauraimage5'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_53b2c9972f5b4471a5f9c66b9c3eae65 }}
        images: 'image5.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ad7a745a38cc4c778d7d45e446068a3f }}/image5:${{ github.sha }}'